# file:https://melpa.org/packages/diff-hl-show-hunk-badge.svg]]

This emacs package shows a [[https://github.com/auto-complete/popup-el][popup]] or a [[https://github.com/tumashu/posframe][posframe]] with the current hunk diff in a buffer under version control. It is based on [[https://github.com/dgutov/diff-hl][diff-hl]].




* Standalone installation

Add this repository to your =load-path=, require it, and enable it for each buffer with =alt-x= =diff-hl-show-hunk-mode=. A global mode =global-diff-hl-show-hunk-mode= is also available.

You can add a hook to enable it when oppening a buffer, as in the code below.

#+begin_src emacs-lisp
(require 'diff-hl-show-hunk)
(add-hook 'prog-mode-hook 'diff-hl-show-hunk-mode)
#+end_src

** Installation from MELPA
This package is (not yet) available on Melpa.

It will be installable with =use-package=
#+begin_src emacs-lisp
(use-package diff-hl-show-hunk
  :ensure t
  :config
  (face-spec-set 'diff-hl-show-hunk-face
                 '((t :background "darkblue") (:height 0.8)))
  (global-diff-hl-show-hunk-mode))
#+end_src



* Similar solutions
See [[https://github.com/dgutov/diff-hl/pull/112][this pull request]] from [[https://github.com/deadtrickster][deadtrickster]]

* If it gets integrated in =diff-hl=

- =diff-hl-show-hunk-narrow=: If =t= (default) the contents of the posframe are narrowed to the current hunk.
- =diff-hl-show-hunk-clicked-line-face=: The face used to highlight the corresponding line of the clicked line. Defaults to inverse video.
- =diff-hl-show-hunk-face=: The face used in the hunk buffer (only used in posframe backend). Defaults to default face with size =0.8=

  The actual backend is specified in =diff-hl-show-hunk-function=. It should be a function that receives as parameters a buffer and a line number. The buffer contains the hunk, and the line corresponds with the line in the original buffer. The default function is =diff-hl-show-hunk-function-default=, that tries to use =diff-hl-show-hunk-posframe= (in GUI) or =diff-hl-show-hunk-popup= (in TUI)
  
** Posframe backend

A posframe is shown with the current hunk. The posframe get the focus, and the hunk can be scrolled and copied with standard commands (cursors, mouse wheel...). To close the posframe, click outside it or press =C-g=.
   
  - =diff-hl-show-hunk-posframe-show-head-line=: if =t=, the posframe shows some useful buttons as a title bar. The title bar allows to move the posframe if dragged.
  - The apearance of the posframe can be configured with the following options, that matches the parameters of [[https://github.com/tumashu/posframe/blob/7b92a54e588889a74d36d51167e067676db7be8a/posframe.el#L372][ =posframe-show= ]] function:
    - =diff-hl-show-hunk-internal-border-width=
    - =diff-hl-show-hunk-internal-border-color=
    - =diff-hl-show-hunk-posframe-poshandler=
    - =diff-hl-show-hunk-posframe-parameters=

** Popup backend

A popup is shown with the current hunk.

   
* Customization
- 
